// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0vNpIqFsPgIvpAFPxpJDTM05XBnuAXlw',
    appId: '1:887634584240:web:cd01899252fbd9f9a81175',
    messagingSenderId: '887634584240',
    projectId: 'tasklist-3dbce',
    authDomain: 'tasklist-3dbce.firebaseapp.com',
    storageBucket: 'tasklist-3dbce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb779g889Qb8QknNs_E2wrNUQjXwmUbFU',
    appId: '1:887634584240:android:dd005669b2d52414a81175',
    messagingSenderId: '887634584240',
    projectId: 'tasklist-3dbce',
    storageBucket: 'tasklist-3dbce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCzVbJRsKaL1ucOY2s0BQTqQy07ejoyS8',
    appId: '1:887634584240:ios:5cf770385bc85284a81175',
    messagingSenderId: '887634584240',
    projectId: 'tasklist-3dbce',
    storageBucket: 'tasklist-3dbce.appspot.com',
    iosClientId: '887634584240-804g1j88hisa5gekcangpeq3e0oln8f4.apps.googleusercontent.com',
    iosBundleId: 'com.example.tasklist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCzVbJRsKaL1ucOY2s0BQTqQy07ejoyS8',
    appId: '1:887634584240:ios:5cf770385bc85284a81175',
    messagingSenderId: '887634584240',
    projectId: 'tasklist-3dbce',
    storageBucket: 'tasklist-3dbce.appspot.com',
    iosClientId: '887634584240-804g1j88hisa5gekcangpeq3e0oln8f4.apps.googleusercontent.com',
    iosBundleId: 'com.example.tasklist',
  );
}
